# Generated by Django 3.2.4 on 2022-12-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=11, unique=True, verbose_name='手机号'), max_length=16, verbose_name='昵称'),
        ),
    ]
