# Generated by Django 3.2.4 on 2023-02-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_day',
            field=models.DateField(auto_now_add=True, verbose_name='创建日'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
